# KNN

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from matplotlib.colors import ListedColormap

In [2]:
etest_data = pd.read_csv("data/etest.csv")
etrain_data = pd.read_csv("data/etrain.csv")
eval_data = pd.read_csv("data/evalidation.csv")
test_data = pd.read_csv("data/test.csv")
train_data = pd.read_csv("data/train.csv")
val_data = pd.read_csv("data/validation.csv")
numeric_features = np.load('numeric_features.npy')

In [18]:
not_num=[]
for i in etest_data.columns:
    if(i not in numeric_features and i != 'target'):
        not_num.append(i)

In [15]:
print(len(not_num))

44
134


In [3]:
print(etrain_data.shape)
print(eval_data.shape)

(26588, 178)
(6647, 178)


Mix feature

In [4]:
etest_data_t = etest_data.drop(['target'],axis = 1)
etrain_data_t = etrain_data.drop(['target'],axis = 1)
eval_data_t = eval_data.drop(['target'],axis = 1)
etrain_data_target = etrain_data[["target"]]
etest_data_target = etest_data[["target"]]
classifier = KNeighborsClassifier(n_neighbors=4)
classifier.fit(etrain_data_t, etrain_data_target)
y_pred = classifier.predict(etest_data_t)
print(confusion_matrix(etest_data_target, y_pred))
print(classification_report(etest_data_target, y_pred))

C:\Users\Anderson\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  import sys


[[1322  482  196   51]
 [ 750  775  448  117]
 [ 395  577  775  363]
 [  96  201  617 1144]]
              precision    recall  f1-score   support

           0       0.52      0.64      0.57      2051
           1       0.38      0.37      0.38      2090
           2       0.38      0.37      0.37      2110
           3       0.68      0.56      0.61      2058

    accuracy                           0.48      8309
   macro avg       0.49      0.48      0.48      8309
weighted avg       0.49      0.48      0.48      8309



Only use numeric features

In [5]:
etest_data_t = etest_data.drop(['target'],axis = 1).loc[:,numeric_features]
etrain_data_t = etrain_data.drop(['target'],axis = 1).loc[:,numeric_features]
eval_data_t = eval_data.drop(['target'],axis = 1).loc[:,numeric_features]
etrain_data_target = etrain_data[["target"]]
etest_data_target = etest_data[["target"]]
classifier = KNeighborsClassifier(n_neighbors=4)
classifier.fit(etrain_data_t, etrain_data_target)
y_pred = classifier.predict(etest_data_t)
print(confusion_matrix(etest_data_target, y_pred))
print(classification_report(etest_data_target, y_pred))

C:\Users\Anderson\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  import sys


[[1596  374   74    7]
 [ 866  845  346   33]
 [ 322  703  888  197]
 [  39  164  641 1214]]
              precision    recall  f1-score   support

           0       0.57      0.78      0.65      2051
           1       0.41      0.40      0.40      2090
           2       0.46      0.42      0.44      2110
           3       0.84      0.59      0.69      2058

    accuracy                           0.55      8309
   macro avg       0.57      0.55      0.55      8309
weighted avg       0.56      0.55      0.55      8309



Only use category features

In [19]:
etest_data_t = etest_data.drop(['target'],axis = 1).loc[:,not_num]
etrain_data_t = etrain_data.drop(['target'],axis = 1).loc[:,not_num]
eval_data_t = eval_data.drop(['target'],axis = 1).loc[:,not_num]
etrain_data_target = etrain_data[["target"]]
etest_data_target = etest_data[["target"]]
classifier = KNeighborsClassifier(n_neighbors=4)
classifier.fit(etrain_data_t, etrain_data_target)
y_pred = classifier.predict(etest_data_t)
print(confusion_matrix(etest_data_target, y_pred))
print(classification_report(etest_data_target, y_pred))

Region_ ARMM  Region_CAR  Region_Caraga  Region_I - Ilocos Region  \
0             0           0              0                         0   
1             0           0              1                         0   
2             0           0              0                         0   
3             0           0              0                         0   
4             0           0              0                         0   

   Region_II - Cagayan Valley  Region_III - Central Luzon  \
0                           1                           0   
1                           0                           0   
2                           0                           0   
3                           0                           0   
4                           0                           0   

   Region_IVA - CALABARZON  Region_IVB - MIMAROPA  \
0                        0                      0   
1                        0                      0   
2                        0                      0   
3                        0                      0   
4                        0                      1   

   Region_IX - Zasmboanga Peninsula  Region_NCR  ...  \
0                                 0           0  ...   
1                                 0           0  ...   
2                                 0           0  ...   
3                                 0           0  ...   
4                                 0           0  ...   

   Main Source of Water Supply_Lake, river, rain and others  \
0                                                  0          
1                                                  0          
2                                                  0          
3                                                  0          
4                                                  0          

   Main Source of Water Supply_Others  \
0                                   0   
1                                   0   
2                                   0   
3                                   0   
4                                   0   

   Main Source of Water Supply_Own use, faucet, community water system  \
0                                                  0                     
1                                                  1                     
2                                                  0                     
3                                                  1                     
4                                                  0                     

   Main Source of Water Supply_Own use, tubed/piped deep well  \
0                                                  0            
1                                                  0            
2                                                  0            
3                                                  0            
4                                                  1            

   Main Source of Water Supply_Peddler  \
0                                    0   
1                                    0   
2                                    0   
3                                    0   
4                                    0   

   Main Source of Water Supply_Protected spring, river, stream, etc  \
0                                                  0                  
1                                                  0                  
2                                                  0                  
3                                                  0                  
4                                                  0                  

   Main Source of Water Supply_Shared, faucet, community water system  \
0                                                  0                    
1                                                  0                    
2                                                  1                    
3                                                  0                    
4                                       

## MDC